### ISSUE TITLE
Importing multidict raises ImportWarning on 3.6

### ISSUE THREAD

**Issue by pitrou** [aio-libs/multidict#79]
```
$ python -We -c "import multidict as x; print(x.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/antoine/miniconda3/envs/dask36/lib/python3.6/site-packages/multidict/__init__.py", line 24, in <module>
    from ._multidict import (MultiDictProxy,
  File "multidict/_multidict.pyx", line 1, in init multidict._multidict (multidict/_multidict.c:14817)
ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
```

**Comment by asvetlov** [comment]
@pitrou `multidict` package does nothing special for `__spec__` attribute.
Looks like it's not the library issue but something which should be solved by Cython.

BTW what is your usage of the library? Does your code rely on aiohttp or is it something different?

**Comment by pitrou** [comment]
Well, this is strange, since other Cython-build modules don't output this warning. Perhaps multidict simply needs to be rebuilt with a more up-to-date Cython?

**Comment by pitrou** [comment]
> BTW what is your usage of the library? Does your code rely on aiohttp or is it something different?

No, we only use `pytest-aiohttp` to be able to write `async def` test methods :-)

**Comment by asvetlov** [comment]
Ok, will release a new version soon.

**Comment by asvetlov** [comment]
Should be fixed by 2.1.6 release.
Please try it out

**Comment by pitrou** [comment]
It doesn't look any better:
```
$ pip install -U multidict
Collecting multidict
  Downloading multidict-2.1.6-cp36-cp36m-manylinux1_x86_64.whl (365kB)
    100% |████████████████████████████████| 368kB 1.4MB/s 
Installing collected packages: multidict
  Found existing installation: multidict 2.1.5
    Uninstalling multidict-2.1.5:
      Successfully uninstalled multidict-2.1.5
Successfully installed multidict-2.1.6

$ python -Wd -c "import multidict; print(multidict.__version__)"
_frozen_importlib:205: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
2.1.6
```

**Comment by cjerdonek** [comment]
I still see this, FYI, using multidict 3.3.2 and Python 3.6.4. Is this a regression for others?

I noticed this when installing aiohttp for the first time (version 2.3.7).

**Comment by asvetlov** [comment]
Honestly I don't know how to fix it.
The message is annoying but harmless.

**Comment by cjerdonek** [comment]
What about the idea of catching the warning at the appropriate place so each end user doesn't need to track the issue down and resolve for themselves?

It could be something along the lines of--

```python
with warnings.catch_warnings():
    warnings.simplefilter('ignore', category=ImportWarning)
    from ._multidict import ...
```

**Comment by asvetlov** [comment]
PR is welcome :)

**Comment by cjerdonek** [comment]
Okay, though I'd want to see if there's an easy way to fix the underlying issue before personally filing a PR to mask the warning.

**Comment by asottile** [comment]
https://github.com/aio-libs/multidict/issues/304 has a proper root cause analysis, should just need a rebuild against cython 0.29.0
